import Image from 'next/image';
import Link from 'next/link';
import { Mountain, Wifi, Car, Coffee, ArrowRight, MapPin, KeyRound, SquareStack, Droplets } from 'lucide-react';
import { Button, Card, Container, SectionHeading } from '@/components/ui';
import { attractions } from '@/data/attractions';
import { EllaHero } from '@/components/ella-hero';
import { GoogleReviewsLink } from '@/components/google-reviews-link';
import { GuestMoments } from '@/components/guest-moments';
import { PropertyViews } from '@/components/property-views';

export default function Home(){
  const features=[[Wifi,'Free WiFi','Reliable connection for relaxed stays'],[Car,'Free Parking','Convenient on-site parking'],[Mountain,'Mountain Views','Misty highland views all around'],[MapPin,'City Views','Ella town lights and rooftops below'],[KeyRound,'Car Hire','Easy transport arranged on request'],[Coffee,'Breakfast','Fresh breakfast to start your day'],[SquareStack,'Private Balcony','Your own outdoor space to unwind'],[Droplets,'Hot Water','Comfortable hot showers anytime']];
  const jsonLd={'@context':'https://schema.org','@type':'LodgingBusiness',name:'Cloud Breeze Villa',address:{'@type':'PostalAddress',addressLocality:'Ella',addressCountry:'Sri Lanka'},description:'A private mountain villa in cool-climate Ella, Sri Lanka.'};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><EllaHero/>
    <section className="section"><Container><div className="grid gap-10 md:grid-cols-2 md:items-center"><div><SectionHeading eyebrow="Mountain calm" title="A villa made for misty mornings and unhurried days." text="Wake to cool Ella air, drink tea against a green mountain horizon and return to a peaceful private home after a day of exploring. Cloud Breeze Villa pairs generous, relaxed spaces with a warm local welcome."/><Link href="/villa" className="inline-flex items-center gap-2 font-bold text-ocean">Discover the villa <ArrowRight size={17}/></Link></div><Image width={680} height={480} sizes="(max-width: 768px) 100vw, 50vw" className="h-80 w-full rounded-2xl object-cover shadow-xl shadow-ink/10" src="/images/nine-arch-bridge.jpg" alt="Train crossing the Nine Arch Bridge in Ella"/></div></Container></section>
    <section className="bg-white py-20"><Container><SectionHeading center eyebrow="At a glance" title="Everything you need to settle into the hills." text="Simple comforts, thoughtful service and beautiful views make every stay feel easy."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,text]:any)=><Card key={title} className="group border border-teal/10 bg-cream/50 p-6 shadow-none transition duration-500 hover:-translate-y-1 hover:border-sand hover:bg-white hover:shadow-xl hover:shadow-teal/10"><span className="mb-6 flex h-11 w-11 items-center justify-center rounded-full bg-sand/60 text-teal transition group-hover:bg-teal group-hover:text-sand"><Icon size={21}/></span><h3 className="text-xl text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></Card>)}</div></Container></section>
    <section className="section"><Container><div className="rounded-3xl bg-sand px-7 py-10 shadow-xl shadow-sand/30 sm:px-12"><p className="eyebrow">Guest feedback</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><div><h2 className="text-3xl text-teal">See what guests are saying</h2><p className="mt-2 text-slate-600">Read the latest unfiltered feedback on our Google Maps listing.</p></div><div className="rounded-2xl bg-ink"><GoogleReviewsLink compact/></div></div></div></Container></section>
    <section className="section bg-white"><Container><SectionHeading eyebrow="The best of Ella" title="Explore the highlands" text="Waterfalls, tea country and unforgettable trails are all close by."/><div className="grid gap-5 md:grid-cols-3">{attractions.slice(0,3).map(a=><Card key={a.name} className="group"><Image width={900} height={600} sizes="(max-width: 768px) 100vw, 33vw" className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" src={a.image} alt={a.name}/><div className="p-5"><p className="eyebrow">{a.distance}</p><h3 className="mt-2 text-xl">{a.name}</h3><p className="mt-2 text-sm text-slate-600">{a.description}</p></div></Card>)}</div><Button href="/attractions" variant="outline" className="mt-8">See all Ella attractions</Button></Container></section>
    <GuestMoments />
    <PropertyViews />
    <section className="bg-teal py-16 text-center text-white"><Container><h2 className="text-4xl">Ready to breathe in Ella?</h2><p className="mx-auto mt-3 max-w-lg text-white/75">Your mountain pause is waiting.</p><Button href="/book" variant="light" className="mt-7">Book Now</Button></Container></section>
  </>;
}
